/**
 * Extended Multi-Agent Orchestration Patterns
 *
 * Implements:
 * 1. Mixture-of-Agents (MoA)
 * 2. Actor-Critic
 * 3. Socratic tutor
 * 4. Prompt Chaining
 * 5. Program-of-Thought (PoT)
 * 6. Skeleton-of-Thought (SoT)
 * 7. Step-Back Abstraction
 * 8. Rejection Sampling (Best-of-N)
 * 9. Self-Correction / Self-Debugging
 */

import type { Agent, AgentOutput, AgentInput, EntityId } from '../../core/index.js';
import { AgentState } from '../../core/index.js';
import { createRunnableAgent } from '../core/agent-adapter.js';
import type { OrchestrableAgent, AgentContext } from '../core/types.js';

export type AnyAgent = Agent | OrchestrableAgent;

/** Helper to run any Agent or OrchestrableAgent cleanly. */
async function runAnyAgent(agent: AnyAgent, prompt: string, context?: Record<string, unknown>): Promise<string> {
    if ('instructions' in agent && typeof agent.run === 'function') {
        const res = await agent.run(prompt, { context } as any);
        return res.text;
    } else {
        const orchestrable = agent as OrchestrableAgent;
        const input: AgentInput = { prompt, context };
        const ctx: AgentContext = {
            agentId: orchestrable.id,
            metadata: context ?? {},
        };
        const out = await orchestrable.run(input, ctx);
        return typeof out.result === 'string' ? out.result : JSON.stringify(out.result);
    }
}

// ── 1. Mixture-of-Agents (MoA) ───────────────────────────────────────────────

export interface MoAConfig {
    readonly name: string;
    readonly description?: string;
    readonly proposers: AnyAgent[];
    readonly aggregator: AnyAgent;
    readonly rounds?: number;
}

export function createMixtureOfAgents(config: MoAConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const rounds = config.rounds ?? 1;
        let lastResponses: string[] = [];

        // In round 1, run all proposers on the raw prompt in parallel
        lastResponses = await Promise.all(
            config.proposers.map(agent => runAnyAgent(agent, input.prompt, input.context))
        );

        // In subsequent rounds, run proposers with the context of previous responses
        for (let round = 2; round <= rounds; round++) {
            const contextText = lastResponses.map((r, i) => `[Agent ${i + 1} Response]:\n${r}`).join('\n\n');
            const roundPrompt = `Task: ${input.prompt}\n\nHere are responses from the previous round of agents:\n${contextText}\n\nReview the responses, identify strengths/weaknesses, and output a refined response.`;
            lastResponses = await Promise.all(
                config.proposers.map(agent => runAnyAgent(agent, roundPrompt, input.context))
            );
        }

        // Final round: aggregator synthesizes all proposer responses
        const aggregatorContext = lastResponses.map((r, i) => `[Proposer ${i + 1} Response]:\n${r}`).join('\n\n');
        const aggregatorPrompt = `Task: ${input.prompt}\n\nHere are multiple candidate responses generated by different agents:\n${aggregatorContext}\n\nSynthesize, verify, and combine these into a single high-quality final response.`;
        const finalResponse = await runAnyAgent(config.aggregator, aggregatorPrompt, input.context);

        return {
            result: finalResponse,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: (config.proposers.length * rounds) + 1,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Mixture-of-Agents consensus model',
        run,
    });
}

// ── 2. Actor-Critic ──────────────────────────────────────────────────────────

export interface ActorCriticConfig {
    readonly name: string;
    readonly description?: string;
    readonly actor: AnyAgent;
    readonly critic: AnyAgent;
    readonly maxRefinements?: number;
    readonly isSatisfactory?: (critique: string) => boolean;
}

export function createActorCritic(config: ActorCriticConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const maxRefinements = config.maxRefinements ?? 3;
        const satisfactoryCheck = config.isSatisfactory ?? ((critique) => {
            const lower = critique.toLowerCase();
            return lower.includes('pass') || lower.includes('satisfactory') || lower.includes('looks good') || (!lower.includes('improve') && !lower.includes('correct') && !lower.includes('error'));
        });

        let currentOutput = await runAnyAgent(config.actor, input.prompt, input.context);
        let currentCritique = '';
        let iterations = 1;

        for (let i = 0; i < maxRefinements; i++) {
            const critiquePrompt = `Original Prompt: ${input.prompt}\n\nProposed Answer:\n${currentOutput}\n\nEvaluate the answer above. Point out errors, style issues, or missing details.`;
            currentCritique = await runAnyAgent(config.critic, critiquePrompt, input.context);
            iterations++;

            if (satisfactoryCheck(currentCritique)) {
                break;
            }

            const refinementPrompt = `Original Prompt: ${input.prompt}\n\nProposed Answer:\n${currentOutput}\n\nFeedback from Reviewer:\n${currentCritique}\n\nRefine and improve your proposed answer based on the feedback.`;
            currentOutput = await runAnyAgent(config.actor, refinementPrompt, input.context);
            iterations++;
        }

        return {
            result: currentOutput,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Actor-Critic refine loop',
        run,
    });
}

// ── 3. Socratic tutor ────────────────────────────────────────────────────────

export interface SocraticConfig {
    readonly name: string;
    readonly description?: string;
    readonly agent: AnyAgent;
    readonly topic?: string;
    readonly instructions?: string;
}

export function createSocraticAgent(config: SocraticConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const topic = config.topic ?? 'the user task';
        const customInstructions = config.instructions ?? '';

        const socraticPrompt = `You are a Socratic tutor guiding the student on the topic: ${topic}.
Do NOT give the direct answer or solution. Instead, ask helpful guiding questions, prompt reflection, or point out contradictions in user responses.
${customInstructions}

Student Input: ${input.prompt}`;

        const output = await runAnyAgent(config.agent, socraticPrompt, input.context);

        return {
            result: output,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: 1,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Socratic tutor agent',
        run,
    });
}

// ── 4. Prompt Chaining ───────────────────────────────────────────────────────

export interface ChainStep {
    readonly name: string;
    readonly agent: AnyAgent;
    readonly template?: (input: string, previousResults: Record<string, string>) => string;
}

export interface PromptChainConfig {
    readonly name: string;
    readonly description?: string;
    readonly steps: ChainStep[];
}

export function createPromptChain(config: PromptChainConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const results: Record<string, string> = {};
        let currentPrompt = input.prompt;

        for (const step of config.steps) {
            const formattedPrompt = step.template
                ? step.template(currentPrompt, results)
                : currentPrompt;

            const res = await runAnyAgent(step.agent, formattedPrompt, input.context);
            results[step.name] = res;
            currentPrompt = res;
        }

        return {
            result: {
                steps: results,
                final: currentPrompt,
            },
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: config.steps.length,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Prompt chaining agent pipeline',
        run,
    });
}

// ── 5. Program-of-Thought (PoT) ──────────────────────────────────────────────

export interface ProgramOfThoughtConfig {
    readonly name: string;
    readonly description?: string;
    readonly agent: AnyAgent;
    readonly executor?: (code: string) => Promise<{ stdout: string; stderr: string; error?: Error }> | { stdout: string; stderr: string; error?: Error };
}

export function createProgramOfThought(config: ProgramOfThoughtConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const defaultExecutor = async (code: string) => {
            try {
                // A safe evaluation wrapper inside node.js/bun
                // If it's a basic mathematical or algorithmic code block, execute it
                // We wrap standard console.log behavior
                let logOutput = '';
                const originalLog = console.log;
                console.log = (...args) => {
                    logOutput += args.map(arg => typeof arg === 'object' ? JSON.stringify(arg) : String(arg)).join(' ') + '\n';
                };
                const fn = new Function(code);
                const val = await fn();
                console.log = originalLog;
                return {
                    stdout: logOutput + (val !== undefined ? `Result: ${val}` : ''),
                    stderr: '',
                };
            } catch (err) {
                return {
                    stdout: '',
                    stderr: err instanceof Error ? err.stack || err.message : String(err),
                    error: err instanceof Error ? err : new Error(String(err)),
                };
            }
        };

        const executor = config.executor ?? defaultExecutor;

        // Prompt the agent to output a executable block of JS code inside a markdown code fence
        const codingPrompt = `${input.prompt}
Please write JavaScript code to solve this problem. Wrap your executable code within \`\`\`javascript ... \`\`\` blocks.
The code should perform the calculations or logical steps and write output using console.log() if necessary.`;

        const codeOutput = await runAnyAgent(config.agent, codingPrompt, input.context);
        const codeMatch = codeOutput.match(/```javascript([\s\S]*?)```/) || codeOutput.match(/```js([\s\S]*?)```/);
        const code = codeMatch ? codeMatch[1]!.trim() : codeOutput;

        const execResult = await executor(code);

        const finalPrompt = `Original Prompt: ${input.prompt}
You wrote the following code:
\`\`\`javascript
${code}
\`\`\`

Here is the execution output:
Stdout:
${execResult.stdout}
Stderr:
${execResult.stderr}

Based on the execution result, formulate the final complete answer.`;

        const finalAnswer = await runAnyAgent(config.agent, finalPrompt, input.context);

        return {
            result: finalAnswer,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: 2,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Program-of-Thought (PoT) computation agent',
        run,
    });
}

// ── 6. Skeleton-of-Thought (SoT) ─────────────────────────────────────────────

export interface SkeletonOfThoughtConfig {
    readonly name: string;
    readonly description?: string;
    readonly planner: AnyAgent;
    readonly worker: AnyAgent;
    readonly parallel?: boolean;
}

export function createSkeletonOfThought(config: SkeletonOfThoughtConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const parallel = config.parallel ?? true;

        const plannerPrompt = `Task: ${input.prompt}
Please decompose this request into a structured outline or skeleton of distinct sections.
Return a valid JSON array of strings, where each element is a clear, self-contained heading or question representing a section to write. E.g.: ["Introduction", "Analysis of X", "Conclusion"].
Do not add any preamble or markdown wrapper, output ONLY the JSON array.`;

        const planOutput = await runAnyAgent(config.planner, plannerPrompt, input.context);
        let sections: string[] = [];
        try {
            const cleanPlan = planOutput.replace(/```json/g, '').replace(/```/g, '').trim();
            sections = JSON.parse(cleanPlan);
            if (!Array.isArray(sections)) {
                throw new Error('Not an array');
            }
        } catch (e) {
            // Fallback: parse lines
            sections = planOutput.split('\n').map(l => l.replace(/^\d+\.\s*/, '').trim()).filter(l => l.length > 0);
        }

        const responses: string[] = [];
        if (parallel) {
            const promises = sections.map(sec => {
                const stepPrompt = `Task Context: ${input.prompt}\n\nPlease write the details for this specific section: "${sec}". Ensure it flow seamlessly and has depth.`;
                return runAnyAgent(config.worker, stepPrompt, input.context);
            });
            const details = await Promise.all(promises);
            for (let i = 0; i < sections.length; i++) {
                responses.push(`## ${sections[i]}\n\n${details[i]}`);
            }
        } else {
            for (const sec of sections) {
                const stepPrompt = `Task Context: ${input.prompt}\n\nPlease write the details for this specific section: "${sec}". Ensure it flow seamlessly and has depth.`;
                const details = await runAnyAgent(config.worker, stepPrompt, input.context);
                responses.push(`## ${sec}\n\n${details}`);
            }
        }

        return {
            result: responses.join('\n\n'),
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: 1 + sections.length,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Skeleton-of-Thought parallel generation agent',
        run,
    });
}

// ── 7. Step-Back Abstraction ─────────────────────────────────────────────────

export interface StepBackConfig {
    readonly name: string;
    readonly description?: string;
    readonly stepBackAgent: AnyAgent;
    readonly solverAgent: AnyAgent;
    readonly generateStepBackPrompt?: (prompt: string) => string;
}

export function createStepBackAgent(config: StepBackConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const defaultPromptGen = (prompt: string) => `Task: ${prompt}
What is the underlying conceptual principle or broader context that defines this specific question? Formulate a step-back conceptual prompt/question and answer it directly.`;

        const stepBackGen = config.generateStepBackPrompt ?? defaultPromptGen;
        const stepBackPrompt = stepBackGen(input.prompt);
        const stepBackContext = await runAnyAgent(config.stepBackAgent, stepBackPrompt, input.context);

        const solverPrompt = `Context information:\n${stepBackContext}\n\nOriginal Question: ${input.prompt}\n\nUsing the conceptual context provided above, solve the original question step-by-step.`;
        const finalOutput = await runAnyAgent(config.solverAgent, solverPrompt, input.context);

        return {
            result: finalOutput,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: 2,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Step-back abstraction model',
        run,
    });
}

// ── 8. Rejection Sampling (Best-of-N) ────────────────────────────────────────

export interface RejectionSamplingConfig {
    readonly name: string;
    readonly description?: string;
    readonly agent: AnyAgent;
    readonly judge: AnyAgent | ((candidate: string) => Promise<number> | number);
    readonly n?: number;
}

export function createRejectionSampling(config: RejectionSamplingConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const n = config.n ?? 3;
        const candidates = await Promise.all(
            Array.from({ length: n }).map(() => runAnyAgent(config.agent, input.prompt, input.context))
        );

        let bestIndex = 0;
        let highestScore = -Infinity;

        if (typeof config.judge === 'function') {
            for (let i = 0; i < candidates.length; i++) {
                const score = await config.judge(candidates[i]!);
                if (score > highestScore) {
                    highestScore = score;
                    bestIndex = i;
                }
            }
        } else {
            const judgeAgent = config.judge;
            const promises = candidates.map(async (cand) => {
                const scorePrompt = `Candidate Answer:\n${cand}\n\nScore this answer on a scale from 0 to 10 based on accuracy, structure, and readability. Return ONLY the numerical score.`;
                const res = await runAnyAgent(judgeAgent, scorePrompt, input.context);
                const score = parseFloat(res.trim()) || 0;
                return score;
            });
            const scores = await Promise.all(promises);
            for (let i = 0; i < scores.length; i++) {
                if (scores[i]! > highestScore) {
                    highestScore = scores[i]!;
                    bestIndex = i;
                }
            }
        }

        return {
            result: candidates[bestIndex]!,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: n + (typeof config.judge === 'function' ? 0 : n),
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Rejection sampling (Best-of-N) agent wrapper',
        run,
    });
}

// ── 9. Self-Correction / Self-Debugging ──────────────────────────────────────

export interface SelfCorrectionConfig {
    readonly name: string;
    readonly description?: string;
    readonly agent: AnyAgent;
    readonly validator: (output: string) => Promise<{ valid: boolean; errors?: string[] }> | { valid: boolean; errors?: string[] };
    readonly maxRetries?: number;
}

export function createSelfCorrection(config: SelfCorrectionConfig): OrchestrableAgent {
    const run = async (input: AgentInput, _ctx: AgentContext): Promise<AgentOutput> => {
        const start = Date.now();
        const maxRetries = config.maxRetries ?? 3;

        let currentResponse = await runAnyAgent(config.agent, input.prompt, input.context);
        let attempts = 1;

        for (let i = 0; i < maxRetries; i++) {
            const check = await config.validator(currentResponse);
            if (check.valid) {
                break;
            }

            const errorText = check.errors?.join('\n') || 'Validation failed.';
            const correctionPrompt = `Original Prompt: ${input.prompt}
Your previous answer:
${currentResponse}

The answer failed validation with the following error(s):
${errorText}

Identify and correct the issues, then write the fully corrected answer.`;

            currentResponse = await runAnyAgent(config.agent, correctionPrompt, input.context);
            attempts++;
        }

        return {
            result: currentResponse,
            state: AgentState.COMPLETED,
            metadata: {
                startTime: new Date(),
                endTime: new Date(),
                durationMs: Date.now() - start,
                iterations: attempts,
            },
        };
    };

    return createRunnableAgent({
        name: config.name,
        description: config.description ?? 'Self-Correction and debugging agent loop',
        run,
    });
}
